<!-- Custom stylesheet -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('wasa/css/checkout.css'); ?>" />

<div class="wasa__product-widget__container">
  <div class="wasa__product-widget__row">    
    <h3 class="wasa__product-widget__heading"><?php echo $this->getLeasingCost(); ?>&thinsp;kr&thinsp;/&thinsp;mån</h3>
    <!-- TODO: Add tooltip -->
    <!-- <span class="wasa_product-widget__tooltip">i</span> -->  
  </div>
  <div>
    <img class="wasa__product-widget__logo"></span>
    <span class="wasa__product-widget__copy">
      Leasing gör det möjligt.
    </span> 
  </div>
</div>