
<?php
$order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);
$baseUrl = Mage::getStoreConfig('payment/advanced_options/request_domain');
?>

<!-- Custom stylesheet -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('wasa/css/checkout.css'); ?>" />

<?php echo $this->getCheckoutURL() ?>

<form name="wkcheckout" method="post" action="<?php echo Mage::helper('wkcheckout')->getPaymentGatewayUrl(); ?>">
  <input type="hidden" name="orderId" value="<?php echo $orderId; ?>">
  <!-- <input type="submit"/> -->
</form>


<script>
    
    var baseUrl=<?php echo json_encode($baseUrl); ?>;


    function httpGet(url, callback)
    {
      var response = null;
      var http = new XMLHttpRequest();      
      http.onreadystatechange = function() {
        callback(this.readyState, this.status, http);
      };
      http.open("GET", url, true);
      http.send(null);
      return response ? response : null;
    }

    function translateObjectContents(prefix, param)
    {
      return '?' + prefix + '=' + param;
    }

    function encodeOrderId() {
      var orderId=<?php echo json_encode($orderId); ?>;
      return orderId;
    }

    var options = {
      onComplete: function(orderReferences){         
        //var wasaOrderId = orderReferences[orderReferences.length - 1]['value'];
        var wasaOrderId = orderReferences.filter(function(a){return a.key==="wasakredit-order-id"})[0].value;
      
        httpGet(baseUrl + '/wkcheckout/checkout/callbackCompleted'
                 + translateObjectContents('order_id', encodeOrderId()) + '&' + 'wasa_order_id=' + wasaOrderId,
                 function(state, status, http) { if(state == 4 && status == 200) { return http.responseText; }
        });
      },
      onRedirect: function(orderReferences){        
        var callbackUrl = httpGet(baseUrl + '/wkcheckout/checkout/callbackRedirected', function(state, status, http) {
          if(state == 4 && status == 200) {
            window.location = http.responseText;
          }
        });                
      },
      onCancel: function(orderReferences){
        httpGet(baseUrl + '/wkcheckout/checkout/callbackCancelled' + translateObjectContents('order_id', encodeOrderId()), function(state, status, http) {
          if(state == 4 && status == 200) {
            
            window.location = http.responseText;     
          }          
        });
      }
    };

    window.wasaCheckout.init(options);

</script>

